### ISSUE TITLE
Getting access error

### ISSUE THREAD

**Issue by SGTGunner** [Anrop/Anrop-Arma3Sync-Manager#19]
@Dahlgren getting the following error when I hit the build button. I checked that the config is right, appears to be correct.

POST /api/arma3sync/build 500 24.482 ms - 958
Error: spawn EACCES
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at Arma3Sync.execute (/usr/src/app/lib/arma3sync.js:36:22)
    at Arma3Sync.build (/usr/src/app/lib/arma3sync.js:18:8)
    at /usr/src/app/api/arma3sync.js:7:15
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)

**Comment by SGTGunner** [comment]
fixed it. Path to JAVA was not correct.
